#!/usr/bin/env python3
"""Dump a 1-bit .icn/.chr file as Uxntal hex so it can be ~included in a ROM.

usage: icn2tal.py LABEL FILE > out.tal
"""
import sys

label, path = sys.argv[1], sys.argv[2]
data = open(path, "rb").read()
print(f"( generated by tools/icn2tal.py from {path}, {len(data)} bytes )")
print(f"@{label}")
for i in range(0, len(data), 16):
    row = data[i:i + 16]
    print("\t" + " ".join(row[j:j + 2].hex() for j in range(0, len(row), 2)))
